### PR TITLE
UINavigationView adds navigationBar's height to contentSizeForViewInPopover

### PR DESCRIPTION
**Pull request by ghost**
I checked, and this is how UIKit behaves.

### CODE REVIEW

**Comment by ghost** [comment]
Added a commit to make the last UITableViewCell in each section except the last use the same darker color for its separator as UIKit

**Comment by BigZaphod** [comment]
Apple's UITableView has no public property named -lastRowInSectionSeparatorColor that I can find. Where does this come from?

**Comment by ghost** [comment]
Sorry, I messed that up by trying to make it as similar to sectionColor as possible - I'll remove the property, should that color still be created in initWithFrame and kept in an ivar?

**Comment by BigZaphod** [comment]
Yeah, keeping it as a private ivar would be better. Do you know if it uses the same color no matter what you choose as a separator color or does it perhaps take the separator color that's given and do some kind of darkening on it? If it's the latter, I wonder if it should configure that particular color as part of the separator color's setter?

**Comment by ghost** [comment]
It always uses the same color.
There's something else I missed though - it only uses the darker separator color for the last cell of a section if the following section has a header, or that section has a footer. I'll have another commit up soon that checks for a header or footer following the cell before it changes the separator color.

**Comment by BigZaphod** [comment]
I'm now closing old pull requests to clean things up. It doesn't mean I don't appreciate this - more likely it means I suck at Git and managing open source and dealing with the fact that things have diverged a lot since the pull request was first opened. :P

**Pull request closed without merging**
