### PR TITLE
Our master branch

### PR DESCRIPTION
**Pull request by zbowling**
I don't normally do this kind of pull request. It's a big one. There are hundreds of commits in this tag. 

There are a lot of changes, including iOS 5 features, 32bit GCC support (fragile abi), some ARC tags to help going forward, a bunch of support added from dmgctrl's branch (minus moving ivars to the implementation because it breaks 32bit support), fixes for beizer path bugs, faster UIImage stretching, UITabBar support merged in from @riquedafreak, a start to UIViewController containment, soem UIKitView fixes, and the list goes on. 

I wish I could break this up (I tried but I just can't at this stage). There is a lot here. Take a look and let me know.

### CODE REVIEW

**Comment by jehiah** [comment]
+1 for getting a lot of the floating work thats been done on various forks back a central location (BigZaphod:master)

**Comment by LinusU** [comment]
+1 from me to, the last comment was 9 months ago, is anything happening?

**Comment by BigZaphod** [comment]
I know there's some awesome stuff in here, but this is just too much for me to parse. I suck with Git as it is, and this is... huge, which is why I've mostly ignored it for so long. I'm now closing these old pull requests to clean things up. It doesn't mean I don't appreciate the offer - more likely it means I suck at Git and managing open source. :P

**Comment by zbowling** [comment]
That sucks. There is a metric ton of fixes and good code. I've moved on from Chameleon to TWUI but there is some awesome stuff here.

**Pull request closed without merging**
