### PR TITLE
Support GC

### PR DESCRIPTION
**Pull request by joshaber**
These are a few changes I had to make to get it to compile with GC support. I haven't tested enough to know if there are any GC-specific issues but at least it builds now :)

### CODE REVIEW

**Comment by BigZaphod** [comment]
github tells me to run this command in the merge help, but when I do I get an error. Any idea what's going on?

$ git pull https://github.com/joshaber/Chameleon.git 3f48736
fatal: Couldn't find remote ref 3f48736

**Comment by joshaber** [comment]
That line should say:
    git pull https://github.com/joshaber/Chameleon.git master

Note the master at the end. Does that do the trick?

**Comment by joshaber** [comment]
Hi Sean,

Did you give up on this one? :) Anything more I can do to help?

**Comment by BigZaphod** [comment]
I think ARC is the way to go.

**Pull request closed without merging**
