### PR TITLE
add static UIFont functions systemFontSize etc

### PR DESCRIPTION
**Pull request by steipete**
makes UIFont more complete

### CODE REVIEW

**Comment by steipete** [comment]
well, it's become something more. Currently my porting efforts halted, missing NSFetchedResultsController...

**Comment by BigZaphod** [comment]
Lots of good stuff here!

I'm unsure how much I like the idea of adding in deprecated stuff. When porting Twitterrific I tended to just get rid of deprecated stuff in that codebase rather than adding them here - although in this case they are reasonably harmless and don't add any real complexity. I know it could be a problem removing them from your own project if your iOS project is targeting an older iOS version, though. Anyway, just throwing that out there. :P It won't stop me from merging this whenever you think it might be ready. :)

**Comment by steipete** [comment]
Thanks!

On the deprecated stuff:
We want maximal compatibility - and this includes deprecated items too. I agree that it shouldn't be used, but in some cases it's not in your hand (like using 3rdparty libraries). In my case there are some references used inside three20, that I don't want to patch out (maybe later).

As those are only constants, they don't really add up any weight, I'd appreciate it if we could merge that :)

**Comment by BigZaphod** [comment]
I could probably find the answer quickly myself... but could we flag deprecated things with whatever flag Apple uses to cause the compiler warning, maybe? I'm probably just being unnecessarily anal. :P

**Comment by AlanQuatermain** [comment]
You can definitely flag stuff— the `NS_AVAILABLE_BUT_DEPRECATED()` macro would do the trick, but you probably just want to use `NS_DEPRECATED` or `__attribute__((deprecated))` directly.

Peter: I can fill out NSFetchedResultsController a bit for you. The tricky stuff is mapping things from one index to another following changes, but now that we're on a desktop we can at least hack in a version with non-optimal memory usage to begin with.

**Comment by steipete** [comment]
yeah, we should. but that signal only works for functions, not those extern NSStrings. 

@interface SomeClass
-method **attribute**((deprecated));
@end

I'll add it!

**Comment by steipete** [comment]
Sorry for rewriting the history, just modified my commits so they can be applied to current master.

@alan - that would be great. I also thought about hacking something together at first, my primary goal is to compile a large project, and then, later, fix the ugly parts. So any help is greatly appreciated.

**Comment by BigZaphod** [comment]
Does NSFetchedResultsController exist in Lion?

**Comment by AlanQuatermain** [comment]
I'm not sure offhand. I don't remember seeing it.

**Comment by steipete** [comment]
I doubt so. I read that CoreData goes in an interesting direction with Lion, bit didn't had time to check it out.

**Comment by BigZaphod** [comment]
Github n00b question: Since this seems to be a large, on-going change, is the normal thing to do to leave this pull request open and wait until you give the go-ahead to merge it into the main branch or does that even matter? If I merged it now as-is and the pull request closed itself, would further changes you make just re-open the pull request or something like that?

(I don't advise learning git one day, and then on the very next day, launching a project that ends up becoming rather popular overnight.. :P)

**Comment by AlanQuatermain** [comment]
Just merge when you want to. We can submit further pull requests later for other commits.

**Comment by steipete** [comment]
Yes, the more correct approach would be: i create a branch, add my changes, open the pull request, and I continue in dev/master branch.

But i just couldn't stop coding ;) And it compiles now - win! Touch Events aren't handled for now, I suppose there is an issue where multiple UIWindows don't send events through. But It's almost 3 in the morning here, I'm done for today.

I just rebased, you can merge everything. I tried the demos, everything looks good here.

And if I've new stuff, I just open another pull request.

**Comment by BigZaphod** [comment]
Ok, thanks guys - good to know! Thanks!

**Comment by BigZaphod** [comment]
I appreciate all the hard work, but please be careful about matching the coding style / spacing / etc. I don't want things to get messy. :) I know not everyone has the same style, and my style may or not may not make sense to everyone, but some I think consistency is probably important for the sake of future maintainability.

**Comment by steipete** [comment]
Thanks for clearing up - I'll try harder to match your style next time.
A small style guide would be great (tabs/spaces, { in same line or next...)

**Comment by BigZaphod** [comment]
A style guide is a good idea. I'll add some notes to the wiki. Thanks!

**Comment by BigZaphod** [comment]
I just noticed that the segmented control code doesn't have the project's usual license header. I'm actually not sure how this normally works. :P The whole project is meant to be licensed with the same BSD license, so I don't know if that means that contributions carry with it an implicit license grant on the part of the original authors or what... Do you happen to know? :P I'm not sure if its legit to just add the header in there? (And if it isn't... who should? So confused! Maybe I'm over-thinking it?)

**Comment by steipete** [comment]
Don't worry, I specifically asked Sam Soffes and he allowed me to relicense some parts of sstoolkit under MIT, as long as we keep his name on top he's more than ok with it. 

Here's a screenshot from the twitter discussion: http://cl.ly/2i2F3q250i191g0e351G

**Comment by steipete** [comment]
BTW, thanks for the Style Guilde, will honor it next time ;)

**Comment by cmelbye** [comment]
I wonder if it would be possible to rebase pull requests like this in the future so that instead of being like 50 commits that are all sort of related to each other, those 50 commits could be squashed into a few commits. Not really necessary, but it would help to clean up the commit log and make it more useful.

**Comment by steipete** [comment]
Sure, it's possible with git to rewrite commits, merge them into bigger ones. But rewriting the history is not a good idea when something is already published, as it breaks user's update. (they need to add --force to get the new data)

I guess Tower can merge commits, if not there's still the console.

**Comment by cmelbye** [comment]
Yeah definitely, I'm talking about using git-rebase for future pull requests right after they've been merged by Sean and before he actually pushes them.

**Comment by BigZaphod** [comment]
Ok... since I'm a total n00b.. :P I read a bit about rebase. I only marginally understand it. What would be the procedure for me to do what you're proposing?

**Comment by steipete** [comment]
Here's a good answer to that. Basically you use git rebase -i (interactive)

http://stackoverflow.com/questions/2302736/trimming-git-checkins-squashing-git-history/2302947#2302947
http://technosorcery.net/2010/2/8/fun-with-the-upcoming-1-7-release-of-git

**Pull request merged**
