### PR TITLE
UITabBar Implementation

### PR DESCRIPTION
**Pull request by feosuna1**
Following pull request implements UITabBar and its associated controller UITabBarController.

A few notes associated with this request:
- I provided a rudimentary implementation of the tab badge but it the graphic I included probably needs a bit of work.
- riquedafreak/Chameleon@ba007b44 was a bit of a hack, it leverages CGRectEqualToRect to test equality of UIEdgeInsets.  A better implementation would be to check equality of each component individual using a strategy defined by Mike Ash (http://www.mikeash.com/pyblog/friday-qa-2011-01-04-practical-floating-point.html). 
- I've already merged the latest master (BigZaphod/Chameleon@1af34026a68134914b9f) with this code, so you should be able to merge in the changes pretty cleanly.

Let me know if you have any questions or concerns.

Enrique

### CODE REVIEW

**Comment by grp** [comment]
Few questions:
- I didn't see UITabBarController calling `-viewWillDisappear:` or `-viewDidAppear:` and friends. Is this done somewhere else?
- Is there a reason for using direct ivar access (e.g. `->_view`) rather than creating a private `-_view` property or method?
- From what I've seen, UITabBarController is **very** specific about the order and when it calls the delegate methods and it's own methods (for example, overriding `-setSelectedViewController:` or `-setSelectedIndex:` will be called in certain situations, but not others). Is that duplicated here, or is it done more by the documentation rather than how UIKit works on the device?

**Comment by feosuna1** [comment]
Thanks for the feedback. My responses are found below:
- UITabBarController doesn't call `-viewWillAppear:` or `-viewWillDisappear:` directly.
  - When the UITabBarController's view is added as a subview to an instance of UIView, UIView calls `-viewWillAppear:` and `-viewDidAppear:` (see it [here](https://github.com/riquedafreak/Chameleon/blob/uitabbar/UIKit/Classes/UIView.m#L204) and 
    [here](https://github.com/riquedafreak/Chameleon/blob/uitabbar/UIKit/Classes/UIView.m#L235)).
  - When the UITabBarController's view is removed from the superview, the UITabBarController's view calls `-viewWillDisappear` and `-viewDidDisappear` (see it [here](https://github.com/riquedafreak/Chameleon/blob/uitabbar/UIKit/Classes/UIView.m#L289) and [here](https://github.com/riquedafreak/Chameleon/blob/uitabbar/UIKit/Classes/UIView.m#L307)).
  - I verified the behavior within the iPhone simulator (iOS 4.3 SDK) and under Chameleon with the commits in question.
  - I also checked with the iOS 4.3 documentation and couldn't find any additional references to calling `-viewWillApear:` or `-viewWillDisappear:` other than those in the UIView class reference documentation.
  - If I missed the mark on this one, let me know and I will dig deeper.
- I accessed the UITabBarItem ivars directly, this was the case of 'I just didn't know what the standard was.' I was followed the precedent set in UIToolbar [implementation](https://github.com/riquedafreak/Chameleon/blob/uitabbar/UIKit/Classes/UIToolbar.m#L61).  I would normally use private accessors (as noted in your comment), but I was trying to conform with the existing code.  This can easily be changed to match the correct standards.
- To your last point, I didn't consider this at all. I tried to use the documentation, but on further review I didn't do two things.  I didn't even come close to completely implementing the documentation's specifications (e.g. I'm missing the `selectedIndex` property) and I didn't give the code enough time to bake to make sure that it mimic actual circumstances (as noted in your comment).

**Comment by feosuna1** [comment]
Accidentally hit the close but.  Arg! Took quick for my own good :/

**Comment by grp** [comment]
Ah, okay, that makes sense. This patch does look awesome, and I'm sure it'll just get better as time goes on.

**Comment by feosuna1** [comment]
I rerolled the pull request based on the feedback and the additional gaps that I identified.  I believe this is a more complete implementation.

**Comment by BigZaphod** [comment]
This looks pretty awesome. I'll merge this next time I get time - I'm not ignoring it! :)

**Comment by BigZaphod** [comment]
I'm now closing old pull requests to clean things up. It doesn't mean I don't appreciate this - more likely it means I suck at Git and managing open source and dealing with the fact that things have diverged a lot since the pull request was first opened. :P

**Pull request closed without merging**
