### PR TITLE
UITableView(Cell), UILabel, UIButton, UIFont, etc. enhancements

### PR DESCRIPTION
**Pull request by ragfield**
These commits contain a bit of missing functionality, a couple of bug fixes, and a few stub method implementations necessary to get my test app up and running.

### CODE REVIEW

**Comment by BigZaphod** [comment]
Very nice work! Unfortunately a couple of concerns jumped out at me as I looked over the diffs:

I'm concerned about the change to UIButton. Did you confirm that this is how Apple's implementation of `-backgroundRectForBounds:` behaves in this case? I had a lot of trouble getting UIButton to match Apple's behaviors for all of the various places it was used in Twitterrific and some of our other projects so I'm especially paranoid about that class. :)

I have a similar reservation about UILabel's change. The documentation for `-textRectForBounds:limitedToNumberOfLines:` says: "The default implementation of this method returns the original bounds rectangle." Is it possible that whatever problem you were seeing with UILabel's behavior might actually be somewhere in `-sizeThatFits:` or something like that? (It's also quite possible that the documentation is wrong and doesn't match the actual behavior, but I think we need to verify that and file radars if necessary.)

**Comment by ragfield** [comment]
Okay, you are correct about UIButton.  I only tested sizeThatFits:.  I incorrectly assumed backgroundRectForBounds: behaved similarly.  It does not.  I relocated that the entirety of that change to sizeThatFits:

https://github.com/ragfield/Chameleon/commit/639e42f1489d51da6e41d0296edaf06727c64229

I'm a newb on github (and git in general, though I've been using Mercurial for a couple  years).  Should I make a new pull request for this changeset?

As far as UILabel goes, it appears the documentation is incorrect.  iOS UILabel's implementation of textRectForBounds:limitedToNumberOfLines: most certainly does not return the bounds passed in, as is demonstrated by this test code (which passes on iOS and on Chameleon with the above change):

```
NSArray* getTestLabels()
{
    NSMutableArray *labels = [NSMutableArray array];

    for(NSInteger size = 10; size <= 24; size += 2) {
        UIFont *font = [UIFont systemFontOfSize: size];

        UILabel *label = [[UILabel alloc] initWithFrame: CGRectZero];
        label.text = @"";
        label.font = font;
        [labels addObject: label];

        label = [[UILabel alloc] initWithFrame: CGRectZero];
        label.text = @"a";
        label.font = font;
        [labels addObject: label];

        label = [[UILabel alloc] initWithFrame: CGRectZero];
        label.text = @"abcdefg";
        label.font = font;
        [labels addObject: label];

        label = [[UILabel alloc] initWithFrame: CGRectZero];
        label.text = @"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        label.font = font;
        [labels addObject: label];
    }

    return labels;
}

void testLabelTextRect()
{
    for(UILabel *label in getTestLabels()) {
        for(NSInteger numberOfLines = 0; numberOfLines < 3; numberOfLines++) {
            CGRect bounds = CGRectMake(10, 10, 1000, 1000);
            CGRect textRect = [label textRectForBounds: bounds limitedToNumberOfLines: numberOfLines];
            NSCAssert(textRect.size.width < 1000, @"");
            NSCAssert(textRect.size.height < 1000, @"");
        }
    }
}
```

I also wrote some tests to verify my change to UIButton.  Are there any plans for unit tests?

```
UIImage *getTestImage(NSInteger w, NSInteger h)
{
    UIGraphicsBeginImageContext(CGSizeMake(w,h));
    UIImage* img = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    NSCAssert((img.size.width == w) && (img.size.height == h), @"");
    return img;
}

NSArray* getTestButtons(UIImage* background)
{
    NSMutableArray *buttons = [NSMutableArray array];

    UIButton *button = [UIButton buttonWithType: UIButtonTypeCustom];
    [button setBackgroundImage: background forState: UIControlStateNormal];
    [buttons addObject: button];

    button = [UIButton buttonWithType: UIButtonTypeCustom];
    [button setBackgroundImage: background forState: UIControlStateNormal];
    [button setTitle: @" " forState: UIControlStateNormal];
    [buttons addObject: button];

    button = [UIButton buttonWithType: UIButtonTypeCustom];
    [button setBackgroundImage: background forState: UIControlStateNormal];
    [button setTitle: @"a" forState: UIControlStateNormal];
    [buttons addObject: button];

    button = [UIButton buttonWithType: UIButtonTypeCustom];
    [button setBackgroundImage: background forState: UIControlStateNormal];
    [button setTitle: @"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" forState: UIControlStateNormal];
    [buttons addObject: button];

    return buttons;
}

void testUIButtonBackgroundImageSizeThatFits(NSInteger w, NSInteger h)
{
    UIImage *img = getTestImage(w, h);
    for(UIButton *button in getTestButtons(img))
    {
        CGSize fitSize = [button sizeThatFits: CGSizeMake(1000, 1000)];
        NSCAssert(fitSize.width >= w, @"");
        NSCAssert(fitSize.height >= h, @"");
    }
}

void testUIButtonBackgroundImageFrame(CGRect frame)
{
    UIImage *img = getTestImage((NSInteger) frame.size.width, (NSInteger) frame.size.height);
    for(UIButton *button in getTestButtons(img)) {
        CGRect r = [button backgroundRectForBounds: CGRectZero];
        NSCAssert(CGRectEqualToRect(r, CGRectZero), @"");

        for(NSInteger i = 0; i < 10; i++) {
            CGRect rect = CGRectMake(rand()/RAND_MAX, rand()/RAND_MAX, rand()/RAND_MAX, rand()/RAND_MAX);
            r = [button backgroundRectForBounds: rect];
            NSCAssert(CGRectEqualToRect(r, rect), @"");
        }
    }
}

void testUIButtonBackgroundImageSize(NSInteger w, NSInteger h)
{
    testUIButtonBackgroundImageSizeThatFits(w, h);
    testUIButtonBackgroundImageFrame(CGRectMake(0, 0, w, h));
    testUIButtonBackgroundImageFrame(CGRectMake(w, h, w, h));
    testUIButtonBackgroundImageFrame(CGRectMake(h, w, w, h));
}

void testUIButtonBackgroundImage()
{
    testUIButtonBackgroundImageSize(1, 1);
    testUIButtonBackgroundImageSize(10, 1);
    testUIButtonBackgroundImageSize(100, 1);
    testUIButtonBackgroundImageSize(1, 10);
    testUIButtonBackgroundImageSize(10, 10);
    testUIButtonBackgroundImageSize(100, 10);
    testUIButtonBackgroundImageSize(1, 100);
    testUIButtonBackgroundImageSize(10, 100);
    testUIButtonBackgroundImageSize(100, 100);
}
```

**Comment by ragfield** [comment]
Ah.  I see my changes automagically made their way into this existing pull request.  Question answered.

**Comment by BigZaphod** [comment]
Awesome - thanks for digging deeper!

Don't worry about being new to git and github - so am I. At least you come from a distributed source control background - I came from svn, learned enough git on Monday to push some older code, and then pushed Chameleon on Tuesday. I'm a bit overwhelmed.. :P As soon as I figure out how to un-destroy whatever I did to my git branch/repo/whatever, I'll get your stuff merged in. This might not happen until tomorrow, though, because it is getting late. :)

As for unit tests - I'd _love_ to see exhaustive tests get built for this stuff - especially stuff that could be run easily against both Apple's UIKit and Chameleon to prove correctness. @brutella has messaged me expressing interest in unit tests. I don't know if you'd want to get in touch with him maybe? Perhaps a new issue should be made for this as a starting point for discussion.

**Pull request merged**
