### PR TITLE
UISwitch and UISegmentedControl implementations.

### PR DESCRIPTION
**Pull request by rafcabezas**
UISwitch and UISegmentedControl implementations. Some other minor fixes. (mouseHovered event also implemented as it's needed for my application, but should be useful in general in Mac applications, and doesn't affect the way UIKit works)

### CODE REVIEW

**Comment by zbowling** [comment]
make sure to check out the @seatme/Chameleon branch. we have a significant enhancements over BigZaphod's branch now (taking code from several branches and bringing it together) and includes some iOS 5 features.

**Comment by rafcabezas** [comment]
Thanks, zbowling. Looks a lot more active too. I'll see if I can open a pull request into that repo/fork then. (Not sure how to go do it. I'll have to git update to that repo first I guess.)

**Comment by zbowling** [comment]
Yeah you can do an integration/feature branch locally, do a 'git remote
add' to the our repo, pull the master from there into your local branch,
then handle and merge issues, then commit into your branch locally, push
the branch to github and send a pull request to us of the feature branch.

Zac

Sent from my next generation secret iPhone I'm not supposed to talk about.

On Nov 30, 2011, at 6:50 PM, Raf <
reply@reply.github.com>
wrote:

Thanks, zbowling. Looks a lot more active too. I'll see if I can open a
pull request into that repo/fork then. (Not sure how to go do it. I'll have
to git update to that repo first I guess.)

---

**Comment by BigZaphod** [comment]
I'm now closing old pull requests to clean things up. It doesn't mean I don't appreciate this - more likely it means I suck at Git and managing open source and dealing with the fact that things have diverged a lot since the pull request was first opened. :P

**Pull request closed without merging**
