### PR TITLE
UINavigationBar/UINavigationItem now update UI when properties change

### PR DESCRIPTION
**Pull request by AlanQuatermain**
There's a simple test app in there too, and various .gitignore files to try to keep the worst of the per-user data from Xcode4 out of the repository.

### CODE REVIEW

**Comment by BigZaphod** [comment]
I'd love it if the spacing was consistent... :) I don't know what's standard in open source projects... does the anal maintainer fix stuff like that, or does he try to make you do it? :P

A further stylistic comment is that I'd have probably gone the route of just sending notifications here instead of using KVO. That may just be a personal preference, though. Generally UIKit doesn't seem to use much KVO. Probably that was for performance reasons that aren't so important on the Mac - although I don't know. I might be very wrong about that, too. :P I just have a general aversion to KVO because for some reason it almost always seems messier than just having a custom notification with a clear name. But again... that might just be me. It's not like I'm the world's most experienced dev. :P (My background is from iOS rather than AppKit and likely it shows all over in my code. :)) What's your thoughts on that? (Not asking you to rewrite your work - I'm just always interested in alternate points of view on matters such as this!)

**Comment by AlanQuatermain** [comment]
The standard is for me to match your style. I intended to, then started typing more quickly, and eventually found I'd reverted back to my usual style & couldn't be bothered combing through everything to change it. I can do that now though ;o)

I used KVO because I've wound up using a fair bit of it in CoreData apps and others recently, and it seemed like the appropriate direction to take. After all, we're looking at changes to particular properties, and synthesized properties already implement KVO notifications. Also, a lot of Apple APIs include documentation on which properties (including non-@property ones) are KVO-compliant. That all adds up to "use that, it's less code, and likely closer to Apple's design".

We could always ask some people on the UIKit team to make a recommendation though ;o)

**Comment by BigZaphod** [comment]
I don't actually know anyone very well on the UIKit team. It'd be awesome to have someone weigh in on this (and maybe other things). Even if privately.. :P If you know anyone well enough, it might be fun to ask! :P

**Comment by AlanQuatermain** [comment]
I sent a (public) message to Chris Parker to see if he would recommend anything different. Might ping him privately later if I don't get a reply. Still pretty early out there though.

**Comment by BigZaphod** [comment]
Thanks! No need to weep! :P

**Pull request merged**
